### ISSUE TITLE
E11000 duplicate key error 

### ISSUE THREAD

**Issue by awatson1978** [Meteor-Community-Packages/meteor-packages#1]
Looks like there's an edge case where duplicate keys are getting generated.  Looks like an `insert()` needs to be replaced with an `upsert()`, or a check on whether files already exist needs to be added.

``` sh
[Wed Feb 24 2016 01:08:57 GMT+0000 (UTC)] WARNING MongoError: E11000 duplicate key error collection:
clinical-redesign_meteor_com.MeteorPackages.SyncState index: _id_ dup key: { : "lastUpdated" }
at Object.Future.wait (/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:398:15)
at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
at [object Object].MongoConnection.(anonymous function) [as insert] (packages/mongo/mongo_driver.js:678:1)
at Object.CollectionHooks.defineAdvice.self (packages/matb33:collection-hooks/insert.js:48:1)
at Object.collection.(anonymous function) [as insert] (packages/matb33:collection-hooks/collection-hooks.js:103:1)
at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:575:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:165:1)
at Function.MeteorPackages.latestPackagesObserve (packages/peerlibrary:meteor-packages/server.coffee:178:16)
at packages/peerlibrary:meteor-packages/server.coffee:313:6
- - - - -
at Object.toError
(/meteor/containers/35163b91-019c-a958-840b-ee410002f3ac/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
at
/meteor/containers/35163b91-019c-a958-840b-ee410002f3ac/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/collection/core.js:116:29
at
/meteor/containers/35163b91-019c-a958-840b-ee410002f3ac/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1195:7
at
/meteor/containers/35163b91-019c-a958-840b-ee410002f3ac/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1903:9
at Server.Base._callHandler
(/meteor/containers/35163b91-019c-a958-840b-ee410002f3ac/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
at
/meteor/containers/35163b91-019c-a958-840b-ee410002f3ac/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
at [object Object].MongoReply.parseBody
(/meteor/containers/35163b91-019c-a958-840b-ee410002f3ac/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
at [object Object].<anonymous>
(/meteor/containers/35163b91-019c-a958-840b-ee410002f3ac/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
at [object Object].emit (events.js:95:17)
at [object Object].<anonymous>
(/meteor/containers/35163b91-019c-a958-840b-ee410002f3ac/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
```

**Comment by mitar** [comment]
There is already a check: https://github.com/peerlibrary/meteor-packages/blob/master/server.coffee#L182

Has the string maybe changed between MongoDB versions?

**Comment by mitar** [comment]
Which version of MongoDB are you using?

**Comment by awatson1978** [comment]
Hmmm.  Well, got that on *.meteor.com when I redeployed.  Whatever MDG is using.
